classdef Explorer
    properties
        sys
        pi
    end
    
    methods
        function obj = Explorer(sys, pi)
            obj.sys = sys;
            obj.pi = pi;
        end
        
       function u = action(obj,x)
            %EXPLORE Get input proposed by exploration algorithm
            %   Given the state x and the system definition (internal), compute
            %   the input generated by a simple random walk exploration algorithm.
            %   The exploration algorithm proposes a random input unless the system
            %   is outside the position constraints, then it tries to recover using
            %   a standard LQR controller.
            %
            %   Args:
            %   x : Current system state.
            %
            %   Returns:
            %	u : Input proposed by exploration algorithm.

            if obj.sys.Px.contains(x)
                u = obj.sys.Pu.randomPoint;
            else
                aux = obj.sys.Pu.project(obj.pi(x));
                u = aux.x;
            end
        end
    end 
end

